config-server:
  ip: localhost

spring:

  application:
    name: book

  profiles:
    active: production


  cloud:
    config:
      uri: http://${config-server.ip}:8888
      label: latest
      profile: production



management:
  endpoints:
    web:
      exposure:
        include: "*"
